fd|FD|FD_Audio|RED|1
pd|PD|PD_Audio|BLUE|1
mpd|mpd|mpd_Audio|MAG|1
mfd|mfd|mfd_Audio|CYN|1
bpd|bpd|bpd_Audio|BLUE|1
bfd|bfd|bfd_Audio|RED|1
mndfd|mndfd|mndfd_Audio|MAG|1
mndpd|mndpd|mndpd_Audio|BLUE|1
blkfd|blkfd|blkfd_Audio|RED|1
blkpd|blkpd|blkpd_Audio|BLUE|1
uptpd|uptpd|uptpd_Audio|BLUE|1
uptfd|uptfd|uptfd_Audio|RED|1
frkpd|frkpd|frkpd_Audio|BLUE|1
frkfd|frkfd|frkfd_Audio|RED|1
mllpd|mllpd|mllpd_Audio|BLUE|1
mllfd|mllfd|mllfd_Audio|RED|1
test1|TEST1|Test1_Audio|YEL|0
test2|TEST2|Test2_Audio|YEL|0
test3|TEST3|Test3_Audio|YEL|0
test4|TEST4|Test4_Audio|YEL|0